FROM alpine:3.4

RUN \
  apk add --update go git make gcc musl-dev && \
  git clone --depth 1 --branch develop https://github.com/cypherium/cypher && \
  (cd go-ethereum && make cypher) && \
  cp go-ethereum/build/bin/cypher /cypher && \
  apk del go git make gcc musl-dev && \
  rm -rf /go-ethereum && rm -rf /var/cache/apk/*

EXPOSE 8545
EXPOSE 30303

ENTRYPOINT ["/cypher"]
